sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
deploy:
  provider: script
  script: npm run release
  skip_cleanup: true
  on:
    branch: master
